### ISSUE TITLE
http(s) result in different view

### ISSUE THREAD

**Issue by jozwa** [Codeinwp/wp-maintenance-mode#148]
1. My website setting "WordPress-adres (URL)" and "Siteadres (URL)" containing my base url starting WITH HTTPS and not HTTP. 
2. When this plugin is active and i'm logged in as admin, i want to view my website. 
3. When i go to the HTTPS i see what i'm build so that is right but when i type in http..mywebsite.. i see the maintenance page while i'm logged in. That looks like a non critical bug to me.

**Comment by georgejipa** [comment]
Hello,

If you login in using the https address and access the http address, I think the WordPress authentification system "believes" that you're not logged in. That's why you see the maintenance mode page.
That being said, please tell me if the problem appears when you login using the http address. Also... I recommend to redirect the http version to the https version.

Thanks.

**Comment by jozwa** [comment]
hi,

If i want to login on the http version, it redirect me automatically to the https version. if i only visit the website, there is no redirect of course. I will go look for a plugin.
When i change the home url to http and i visit the page while i was logged in, both http and https, work fine, no maintenance page and no redirect for now. That looks like 2 different reactions (http and https as home url).
Maybe there is something to check in the code.

Regards.
