### ISSUE TITLE
Make media files unavailable when maintenance mode is activated

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/wp-maintenance-mode#294]
Currently, if the maintenance mode is activated, the images from the media library can still be accessed using their link.

Would it be possible to extend the maintenance mode to the media files as well so they won't be visible with the link when the maintenance mode is activated?

A user asked this [here](https://wordpress.org/support/topic/images-still-accessible-and-multi-site/).

**Comment by girishpanchal30** [comment]
Hi @MarinescuLucia,

I think it seems to be not possible to make media files unavailable when a user opens media using the full URL.
We can not handle it because the media URL opens in the browser with a folder path like wp-content/uploads/*

It's possible if we add `.htaccess` file in **wp-content/uploads/** directory with below `htaccess rules.`

```
Order deny,allow
Deny from all
<Files ~ "(51784363093_647010eadf_k.jpg|test.txt)$"> #Allowed image file path.
Allow from all
</Files>
```

cc @selul
Thanks

**Comment by selul** [comment]
@girishpanchal30 agree, I think we can have a doc on what they could add in the htaccess to do this.
