### ISSUE TITLE
Subscribe form not registering subscribers

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/wp-maintenance-mode#303]
Some users reported that if they have the subscribe module activated and an email is added in the subscribe field, it doesn't appear in Modules -> Subscribe -> Stats, that number remains 0. I tried to replicate this on multiple instances, but for me it works properly every time. However, there are a couple of users that encounter this issue, so maybe there is something happening here. One of them said that after he adds an email, a security popup like the one from [this issue](https://github.com/Codeinwp/wp-maintenance-mode/issues/302) appears for him, but it doesn't appear for me.

Reported [here](https://wordpress.org/support/topic/subscriptions-not-working-9/) and [here](https://wordpress.org/support/topic/subscriber-count-stays-0/).

**Comment by leonardolinoss** [comment]
Good afternoon.
I'm Leonardo, from the interior of the State of Pernambuco, Brazil.
I'm having the same problem when I use boot. When I disable the boot and let the countdown, the email subscription works normally. I would really appreciate it if someone could see what's wrong, as I followed all the procedures in these posts that deal with the same subject, but the boot inscription doesn't work, causing this screen security message. Thank you very much. Anyone who wants access, please get in touch
![Imagem1](https://user-images.githubusercontent.com/68669458/183301706-8cc3bc3b-9ea2-48e3-a430-fad81b461893.png)
.

**Comment by leonardolinoss** [comment]
Thanks to the developers involved. The issue has been resolved in version 2.4.7. Without wanting to abuse the goodwill, I have a suggestion. In the registration forms we have the email address and the date/time when the boot was sent. However, I think the name should also appear on the form, as since we will be sending a first email to the customer, I think it is correct to call them by name. This gives a more personal and close character to the subscriber, making loyalty easier. Thanks again guys!

**Comment by selul** [comment]
Thanks for your feedback! I've created a new feature request based on your comment.
