### ISSUE TITLE
There should be a Skip button on the Onboarding Import section [Feature request]

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/wp-maintenance-mode#345]
### Description

Hey, I am making this feature request after receiving feedback from many different users on the review section of the plugin on the wp.org forum and they are not satisfied with the changes that we have introduced in the plugin after version 2.4.7.

The changes that were introduced :

1. Adds compatibility with Block Editor or any page builder for building the maintenance mode page.
2. Adds coming soon and maintenance mode starting templates.
3. Installing the Otter plugin after the import process.

However, some users have liked the above enhancement and gave us a very positive review on the forum and have started using the Otter plugin as well but some users feel that they are being forced to install another plugin in order to make the LightStart Plugin (the New rebranded name) works for them and have suggested that there should be a skip button on the Start page where the users are asked to choose a template. This should skip the process and directly redirect them to the settings page of the plugin.

### Reference
Wp.org review section: https://wordpress.org/support/plugin/wp-maintenance-mode/reviews/

**Comment by ineagu** [comment]
I was looking into this and I think we can further tweak this approach to have users less frustrated. While we can't skip Otter, we can make it more clear that it would be installed, the issue seems to be more that they felt it was added without their approval.

This would also be an issue as we plan to recommend Optimole.

I am not sure how complex it is to open a popup once the user clicks on a template to import and mention that Otter would also be installed (with a checkbox that can't be disabled) and have Optimole as optional ( checkbox that can be disabled) , as we do have in Neve.

The popup would have 2 buttons; Import  & a text version "I don't want a maintenance page template", which would skip this and redirect users to the settings page.

curious of your thoughts @JohnPixle @HardeepAsrani

**Comment by ineagu** [comment]
I would guesstimate that 90% would go with the import option, so we would get Otter installed, without as much trouble and annoyance.

**Comment by selul** [comment]
@ineagu for Optimole I would consider a separate approach as we did in Feedzy and starter sites. 

TBH, adding a modal seems wrong for me since the wizard is already in a canvas mode.

**Comment by ineagu** [comment]
okay, I would edit my comment and exclude Optimole reference.

**Comment by JohnPixle** [comment]
I am also looking at the reviews regularly and it's either 5 stars or 1 star. As you say, the low ratings stem from the fact that we install Otter, seemingly without their approval. Also, some users mention that they cannot bypass the wizard / import flow, which is not true.

I will follow up on this, but here are some quick thoughts for now:

I believe that apart from Otter, we should consider if it makes sense to provide 1-2 templates with core blocks. We will not have so much design flexibility there without Otter, but it will be baseline-ok. Then, we should give them the option to choose between those low-key core templates, and the Otter ones. Currently, we offer them no option. It's either Otter or nothing(create from scratch). And even in the case that they choose initially the core templates, they will still be exposed to the Otter-powered ones in the library, so they can use them anytime.

If they compare the Otter templates with the core ones, they should immediately spot the difference. 

I also think that this should happen in the wizard flow, somehow. We can integrate the Optimole option inside the wizard flow as well if you want.

Regarding the popup:
Not a fan of a popup to be honest. But if we want to use it, it can only take place just once: When they import a template that requires Otter, and they dont already have Otter activated. 

If they import a template that required Otter, then there is no need to open a popup the second time, because Otter will already be installed.

**Comment by ineagu** [comment]
Regarding your canvas comment, maybe others have other ideas on how we can make this more clear. For me as a user, I didn't realise the context was a canvas, I thought is just a normal page.

**Comment by JohnPixle** [comment]
I agree, in the wizard this is the only reference for Otter. We can do better. 

![Screenshot 2022-11-17 at 4 37 31 PM](https://user-images.githubusercontent.com/4193672/202475183-affeabbf-1ea8-41ab-9b2d-8d12984b7c53.png)

--- 

I think we can do better, and clarify things in various ways. Rough mockup 👇🏻

![Wizard - Step 1  - Landing](https://user-images.githubusercontent.com/4193672/202477339-7452cb87-f11f-4bc7-bb02-aa984f2be107.png)

**Comment by ineagu** [comment]
That’s a great solution. We don’t need to overdo it, we’re not asking for money :)

The top bar is perfect, the button can stay as Continue and the 2nd button can be “I don’t want a [page-type] template.”

Your wording is making otter look more as an ad that we disclaim, while I try to position it more as a tool that you need and would benefit you and we strongly recommend, without forcing you, to use it.

**Comment by ineagu** [comment]
We can even have a link on the otter mention in the top notice to wordpress org repo, so they can check the details & reviews

**Comment by JohnPixle** [comment]
I agree about the message. I'm empty of ideas at the moment regarding the wording, but i will follow up. Meanwhile if you or anyone else has any specific suggestions, feel free to share and I will update the mockup.

Regarding the button, I am not sure if it will be technically possible to include the `[page-type] `in the button text, because the user will need to click any of the three thumbnails in order to "capture" the page type. 

What we can do however is to have the "Coming Soon" thumbnail pre-selected (so the button by default will say “I don’t want a `Coming Soon` template.”)

At the current version if I recall correctly, the "Continue" button is inactive until a user clicks any of the three thumbnails.

Worst case scenario, the second button can be just “I don’t want to use a template”, but we'll try to make it work as you suggested.

**Comment by ineagu** [comment]
okay, we can then stick to your original messaging, just keep Continue instead of Continue with Otter. Is still much better than what we have right now, what do you think?

**Comment by JohnPixle** [comment]
We can use either the original messaging or a second attempt, in case you find it better:

> These templates make use of Otter Blocks powerful features, which will be installed and activated. Learn more about Otter.


![Screenshot 2022-11-18 at 1 43 24 PM](https://user-images.githubusercontent.com/4193672/202697752-168d5dd1-cbe4-42df-8434-00918f6b4f90.png)

**Comment by ineagu** [comment]
@selul do you have any comments on this? if not I think we can implement it like this and should still continue to give good exposure to Otter.

As a note I think the notice need to be present in this format in the templates tab as well, instead of the small text at the end.

**Comment by selul** [comment]
I don't have anything to add, it looks to get started.

**Comment by JohnPixle** [comment]
> As a note I think the notice need to be present in this format in the templates tab as well, instead of the small text at the end.

Noted 👍🏻 

@arinaturcu I will be around for whenever you need any clarifications on this! Please don't hesitate to ask. I will clean-up and share the figmas for both wizard and template tab meanwhile and follow up here.

**Comment by arinaturcu** [comment]
Alright @JohnPixle, thanks!

**Comment by selul** [comment]
@solaceten thank you for your thoughts. 

You can just uninstall otter for now; once we have this one, you can skip the installation as well. 

we will look into the custom template thing as well.

**Comment by selul** [comment]
@solaceten another thing here is that you can use any page created with or without Otter and set that up as maintenance page.

**Comment by JohnPixle** [comment]
@arinaturcu Here is a [Figma link](https://www.figma.com/file/r1pLMeeq4nhynBlCKY6mOQ/LightStart---Coming-Soon-pages?node-id=642%3A2935&t=W7QlJjFoTEnu7zCF-1) for the related mockups for this. I will summarise:

![Screenshot 2022-11-24 at 12 24 20 PM](https://user-images.githubusercontent.com/4193672/203760332-c5da7a25-c540-4610-b584-e64497e0580a.png)

- [ ] We should add the Otter Notice at the onboarding wizard and the template library tab as well, as shown in the mockups. The Text link in the notice should take the users to Otter's plugin page in the repository

- [ ] At the wizard, the text in the buttons changes. 

- [ ] The intro text at the wizard also changes to "Choose the type of template you want, powered by Otter Blocks. You can always customise your layout." Open to suggestions on this one!

![Screenshot 2022-11-24 at 12 27 35 PM](https://user-images.githubusercontent.com/4193672/203761031-7afaabb4-5f6f-4ec1-a1c2-709f26000c0d.png)

- [ ] As per Ionut's suggestion, can we have the text on the button change based on what type of template the user has selected in the thumbnail section? So the button would change to "I don't want a _Landing Page_ Template". If it's too much trouble, we can leave it generic as "I don't want to use a template".

![Screenshot 2022-11-24 at 12 24 08 PM](https://user-images.githubusercontent.com/4193672/203760435-fc93c490-8edb-41b8-8d6a-8d4e1b6471e9.png)



Let me know if I can help in any other way with this 👍🏻
