### ISSUE TITLE
Templates display & quality

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/wp-maintenance-mode#347]
@HardeepAsrani I am not sure if it is Optimole, but the images don't look sharp, neither in the initial onboarding nor here: https://vertis.d.pr/i/ImQE83. They also get one on top of another.

**Comment by HardeepAsrani** [comment]
Can you look into it when you have time? I can't reproduce the overflow of images on my side but specially when you're using a ratina display, the images don't look very good, so we can use maybe better quality screenshots. @arinaturcu

**Comment by arinaturcu** [comment]
> I can't reproduce the overflow of images on my side

I also couldn't, @ineagu can you provide some instructions on how to reproduce it?

Regarding the templates screenshots, sure we can replace them with better quality ones.

**Comment by ineagu** [comment]
it was on tastewp, so maybe something from their side, we can ignore it then and take care of the screenshots for both onboarding and templates screen.

**Comment by arinaturcu** [comment]
I also tested on Tastewp. Maybe there could be some CSS class conflicts. Did you have other plugins installed besides Optimole? 

Anyway, I should note that it should be a good idea to prefix the CSS classes to avoid this.

**Comment by JohnPixle** [comment]
The images overflow is something that I couldn't replicate either.

Regarding the thumbnails though, we already had [an issue](https://github.com/Codeinwp/wp-maintenance-mode/pull/336#issuecomment-1291849691) prior to the last update, with images being harshly resized from their original size (which was quite big).  Not sure if this problem stemmed from Optimole's compression or something else.

Attempting to fix the issue, I had personally re-created the thumbnails in the final sizes that would show up in the library (380 x 405), but I think this was partly a mistake, because when seen in a retina display, they will be scaled up and pixelated.

I did a quick export of the thumbnails in x2 the size, and I am uploading them in Zips here. I think we should test and see if this fixes the issue. I also have a MBP with retina display and I can check. 

Please keep in mind that these thumbnails have already been optimised with tinypng. I am not sure if Optimole will add more compression on them, and if this will be an issue.

[landing pages.zip](https://github.com/Codeinwp/wp-maintenance-mode/files/10056263/landing.pages.zip)
[maintenance.zip](https://github.com/Codeinwp/wp-maintenance-mode/files/10056261/maintenance.zip)
[coming soon.zip](https://github.com/Codeinwp/wp-maintenance-mode/files/10056262/coming.soon.zip)

Let me know if this helps and if I can be of any further assistance.
